/*
 * Copyright (C) 2016 thomas.kercheval
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package USACities;

/**
 *
 * @author thomas.kercheval
 */
public class CitiesGUI extends javax.swing.JFrame {

    /**
     * Creates new form CitiesGUI
     */
    public CitiesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButtonGroup = new javax.swing.ButtonGroup();
        titleJPanel = new javax.swing.JPanel();
        logoJLabel1 = new javax.swing.JLabel();
        titleJLabel1 = new javax.swing.JLabel();
        listJPanel1 = new javax.swing.JPanel();
        displayJPanel1 = new javax.swing.JPanel();
        controlJPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        citiesJMenuBar = new javax.swing.JMenuBar();
        fileJMenu1 = new javax.swing.JMenu();
        clearJenuItem = new javax.swing.JMenuItem();
        printJenuItem = new javax.swing.JMenuItem();
        fileSeperator = new javax.swing.JPopupMenu.Separator();
        exitJMenuItem = new javax.swing.JMenuItem();
        sortJMenu = new javax.swing.JMenu();
        nameJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        popJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        actionJMenu = new javax.swing.JMenu();
        addJenuItem = new javax.swing.JMenuItem();
        editJMenuItem = new javax.swing.JMenuItem();
        deleteJenuItem = new javax.swing.JMenuItem();
        searchJMenuItem = new javax.swing.JMenuItem();
        HelpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Large USA Cities");

        logoJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/USACities/buckinghamfountainsmall.jpg"))); // NOI18N

        titleJLabel1.setFont(new java.awt.Font("Old English Text MT", 2, 36)); // NOI18N
        titleJLabel1.setForeground(new java.awt.Color(0, 33, 46));
        titleJLabel1.setText("Large Cities in USA");

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logoJLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(titleJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoJLabel1))
                    .addComponent(titleJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(titleJPanel, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout listJPanel1Layout = new javax.swing.GroupLayout(listJPanel1);
        listJPanel1.setLayout(listJPanel1Layout);
        listJPanel1Layout.setHorizontalGroup(
            listJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        listJPanel1Layout.setVerticalGroup(
            listJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        getContentPane().add(listJPanel1, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout displayJPanel1Layout = new javax.swing.GroupLayout(displayJPanel1);
        displayJPanel1.setLayout(displayJPanel1Layout);
        displayJPanel1Layout.setHorizontalGroup(
            displayJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        displayJPanel1Layout.setVerticalGroup(
            displayJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        getContentPane().add(displayJPanel1, java.awt.BorderLayout.CENTER);

        controlJPanel1.setLayout(new java.awt.GridLayout(1, 4, 3, 3));

        jButton1.setText("jButton1");
        controlJPanel1.add(jButton1);

        getContentPane().add(controlJPanel1, java.awt.BorderLayout.SOUTH);

        fileJMenu1.setMnemonic('F');
        fileJMenu1.setText("File");

        clearJenuItem.setMnemonic('c');
        clearJenuItem.setText("Clear");
        fileJMenu1.add(clearJenuItem);

        printJenuItem.setMnemonic('p');
        printJenuItem.setText("Print");
        fileJMenu1.add(printJenuItem);
        fileJMenu1.add(fileSeperator);

        exitJMenuItem.setMnemonic('x');
        exitJMenuItem.setText("Exit");
        fileJMenu1.add(exitJMenuItem);

        citiesJMenuBar.add(fileJMenu1);

        sortJMenu.setMnemonic('S');
        sortJMenu.setText("Sort");

        menuButtonGroup.add(nameJRadioButtonMenuItem);
        nameJRadioButtonMenuItem.setMnemonic('n');
        nameJRadioButtonMenuItem.setText("By Name");
        sortJMenu.add(nameJRadioButtonMenuItem);

        menuButtonGroup.add(popJRadioButtonMenuItem);
        popJRadioButtonMenuItem.setMnemonic('b');
        popJRadioButtonMenuItem.setSelected(true);
        popJRadioButtonMenuItem.setText("By Population");
        sortJMenu.add(popJRadioButtonMenuItem);

        citiesJMenuBar.add(sortJMenu);

        actionJMenu.setMnemonic('T');
        actionJMenu.setText("DB Management");

        addJenuItem.setMnemonic('a');
        addJenuItem.setText("Add New City");
        actionJMenu.add(addJenuItem);

        editJMenuItem.setMnemonic('e');
        editJMenuItem.setText("Edit City");
        actionJMenu.add(editJMenuItem);

        deleteJenuItem.setMnemonic('d');
        deleteJenuItem.setText("Delete City");
        actionJMenu.add(deleteJenuItem);

        searchJMenuItem.setMnemonic('S');
        searchJMenuItem.setText("Search City");
        actionJMenu.add(searchJMenuItem);

        citiesJMenuBar.add(actionJMenu);

        HelpJMenu.setMnemonic('H');
        HelpJMenu.setText("Help");

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        HelpJMenu.add(aboutJMenuItem);

        citiesJMenuBar.add(HelpJMenu);

        setJMenuBar(citiesJMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitiesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu HelpJMenu;
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JMenu actionJMenu;
    private javax.swing.JMenuItem addJenuItem;
    private javax.swing.JMenuBar citiesJMenuBar;
    private javax.swing.JMenuItem clearJenuItem;
    private javax.swing.JPanel controlJPanel1;
    private javax.swing.JMenuItem deleteJenuItem;
    private javax.swing.JPanel displayJPanel1;
    private javax.swing.JMenuItem editJMenuItem;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenu fileJMenu1;
    private javax.swing.JPopupMenu.Separator fileSeperator;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel listJPanel1;
    private javax.swing.JLabel logoJLabel1;
    private javax.swing.ButtonGroup menuButtonGroup;
    private javax.swing.JRadioButtonMenuItem nameJRadioButtonMenuItem;
    private javax.swing.JRadioButtonMenuItem popJRadioButtonMenuItem;
    private javax.swing.JMenuItem printJenuItem;
    private javax.swing.JMenuItem searchJMenuItem;
    private javax.swing.JMenu sortJMenu;
    private javax.swing.JLabel titleJLabel1;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}
